[package]
name = "atri_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atri_ffi = { path = "../atri_ffi" }
atri_macros = { path = "../atri_macros" }
