name: Build

on:
  push:
    tags:
      - '*'
    #pull_request: [ master ]
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        target:
          - { name: Linux, os: ubuntu-latest, tool: x86_64-unknown-linux-musl }
          - { name: macOSx86, os: macos-latest, tool: x86_64-apple-darwin }
          - { name: Windows, os: windows-2022, tool: x86_64-pc-windows-msvc }

        version:
            - nightly

    name: ${{ matrix.target.name }} / ${{ matrix.version }}
    runs-on: ${{ matrix.target.os }}

    env:
      CI: 1
      CARGO_INCREMENTAL: 0

    steps:
      - uses: actions/checkout@v2

      - name: Linux install Musl
        if: matrix.target.tool == 'x86_64-unknown-linux-musl'
        run: sudo apt update && sudo apt install -y musl-tools musl-dev

      - name: Install rust toolchain
        run: |
          rustup default nightly
          rustup target add ${{ matrix.target.tool }}

      - name: Test
        run: cargo test --target ${{ matrix.target.tool }}

      - name: Build
        run: cargo build --target ${{ matrix.target.tool }}