name: Build

on:
  push:
    tags:
      - '*'
    #pull_request: [ master ]
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        target:
          - { name: macOSx86, os: macos-latest, tool: x86_64-apple-darwin }
          - { name: Linux, os: ubuntu-latest, tool: x86_64-unknown-linux-musl }
          - { name: Windows, os: windows-2022, tool: x86_64-pc-windows-msvc }

        version:
            - nightly

    name: ${{ matrix.target.name }} / ${{ matrix.version }}
    runs-on: ${{ matrix.target.os }}

    env:
      CI: 1
      CARGO_INCREMENTAL: 0

    steps:
      - uses: actions/checkout@v2

      - name: Install Musl
        if: matrix.target.tool == 'x86_64-unknown-linux-musl'
        run: sudo apt update && sudo apt install -y musl-tools musl-dev

      - name: Install rust toolchain
        run: |
          rustup target add x86_64-unknown-linux-musl

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-${{ matrix.target.tool }}
          profile: minimal

      - name: Override rustup toolchain
        run: rustup default nightly

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build