name: Deploy

on:
  push:
    branches: [ pages ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: atri_doc

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn install --frozen-lockfile

      - run: yarn add --dev vitepress vue

      - name: Build
        run: yarn docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: atri_doc/docs/.vitepress/dist
