name: PullRequest

on:
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: Linux-x64, os: ubuntu-latest }
          - { name: macOS-x64, os: macos-latest }
          - { name: Windows-x64, os: windows-latest }

    name: ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}

    env:
      CI: 1
      CARGO_INCREMENTAL: 0

    steps:
      - uses: actions/checkout@v3

      - name: Setup rust toolchain
        run: rustup default nightly

      - name: Test
        run: cargo test